name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'version: major'
  minor:
    labels:
      - 'version: minor'
  patch:
    labels:
      - 'version: patch'
  default: patch
categories:
  - title: '🚀 New Features'
    label: 'feature'
  - title: '🛠 Improvements'
    label: 'improvement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '🏷 Internal'
    label: 'internal'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes in this release
  $CHANGES