#!/bin/bash

# Path to the commit message file passed by Git
COMMIT_MSG_FILE="$1"

# Read the commit message
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE" | tr -d '\n')

REQUIRED_PATTERNS=("Major Update: " "Minor Update: " "Documentation Update: " "Bug Fix: " "Security Fix: " "Build: " "CI: " "Revert " "Release: " "Merge " "Hotfix: " "New Feature: " "Improvement: " "Performance: " "Style: " "WIP: " "[auto-bump]")

PATTERN_FOUND=0
for PATTERN in "${REQUIRED_PATTERNS[@]}"; do
    if [[ $COMMIT_MSG == *"$PATTERN"* ]]; then
        PATTERN_FOUND=1
        break
    fi
done

if [[ $PATTERN_FOUND -eq 0 ]]; then
    echo "error: Commit message: '$COMMIT_MSG' does not contain any of the required patterns. Please include one."
    exit 1
fi