name: Commit Message Lint

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.github_token }}
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Lint Commit Messages
      run: |
        if [[ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]]; then
          COMMIT_MESSAGES=$(git log --format=%s ${{ github.event.before }}..${{ github.event.after }})
        else
          COMMIT_MESSAGES=$(git log --format=%s -n 1 ${{ github.event.after }})
        fi
        REQUIRED_PATTERNS=("Major Update: " "Minor Update: " "Documentation Update: " "Bug Fix: " "Security Fix: " "Build: " "CI: " "Revert " "Release: " "Merge " "Hotfix: " "New Feature: " "Improvement: " "Performance: " "Style: " "WIP: " "[auto-bump]")

        PATTERN_FOUND=0
        for PATTERN in "${REQUIRED_PATTERNS[@]}"; do
          if [[ $COMMIT_MESSAGES == *"$PATTERN"* ]]; then
            PATTERN_FOUND=1
            break
          fi
        done

        if [[ $PATTERN_FOUND -eq 0 ]]; then
          echo "error: Commit message: '$COMMIT_MESSAGES' does not contain any of the required patterns. Please include one."
          exit 1
        fi