name: Create Artifact

on:
    workflow_run:
        workflows: ["Version Updates"]
        types:
            - completed

jobs:
  zip:
    runs-on: ubuntu-20.04
    if: github.event.workflow_run.conclusion == 'success'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from manifest.json
      run: |
         sudo apt-get install -y jq
         VERSION=$(jq -r .version manifest.json)
         echo "CURRENT_RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create directory for artifact and copy specific files
      run: |
        mkdir YouTube_Max_Quality_Switcher_v${CURRENT_RELEASE_VERSION}
        cp manifest.json YouTube_Max_Quality_Switcher_v${CURRENT_RELEASE_VERSION}
        cp -r ./scripts ./media ./html ./styles YouTube_Max_Quality_Switcher_v${CURRENT_RELEASE_VERSION}/

    - name: Upload directory as artifact
      uses: actions/upload-artifact@v3
      with:
        name: YouTube_Max_Quality_Switcher_v${{ env.CURRENT_RELEASE_VERSION }}.zip
        path: YouTube_Max_Quality_Switcher_v${{ env.CURRENT_RELEASE_VERSION }}