name: Version Updates

on:
  pull_request:
    types: [closed]
    branches:
      - master

concurrency: 
  group: version-bump
  cancel-in-progress: true

jobs:
  update-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.github_token }}
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Check for [auto-bump] in commit message
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1)
          if [[ $COMMIT_MSG == *"[auto-bump]"* ]]; then
            echo "[auto-bump] detected in commit message. Exiting workflow."
            exit 78
          fi

      - name: Install GitHub CLI
<<<<<<< HEAD
        uses: cli/cli-action@v1
        with:
          token: ${{ secrets.github_token }}        
=======
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh      
          gh auth login --with-token <<< "${{ secrets.github_token }}"
>>>>>>> 7249ea2 (Develop (#3))
          
      - name: Determine version bump
        id: determine-version
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1)
          BUMP="none"
          if [[ $COMMIT_MSG == "Merge pull request #"* ]]; then
            PR_NUMBER=$(echo $COMMIT_MSG | grep -o '#[0-9]\+' | grep -o '[0-9]\+')
            COMMIT_MSGS=$(gh pr view $PR_NUMBER --json commits -q ".commits[].commit.message")
      
            echo "$COMMIT_MSGS" | while IFS= read -r msg; do
              if [[ $msg == *"Release: "* ]]; then
                BUMP="major"
                break
              elif [[ $msg == *("Major Update: "*|"New Feature: "*|"Improvement: "*|"Performance: "*|"Bug Fix: "*|"Security Fix: "*|"Hotfix: "*) ]]; then
                BUMP="minor"
              elif [[ $BUMP != "minor" && $msg == *("Minor Update: "*|"Documentation Update: "*|"Build: "*|"CI: "*|"Revert "*|"Merge "*|"Style: "*) ]]; then
                BUMP="patch"
              fi
            done
          fi
      
          echo "Bump: $BUMP"
          echo "bump=$BUMP" >> $GITHUB_ENV

      - name: Update manifest.json
        if: env.bump != 'none' # Use env here instead of steps.determine-version.outputs
        run: |
          sudo apt-get install -y jq
          
          CURRENT_VERSION=$(jq -r .version manifest.json)
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}

          if [[ "${{ env.bump }}" == "major" ]]; then
            NEW_ARTIFACT_VERSION="$((MAJOR + 1)).0.0"
          elif [[ "${{ env.bump }}" == "minor" ]]; then
            NEW_ARTIFACT_VERSION="${MAJOR}.$((MINOR + 1)).0"
          else
            NEW_ARTIFACT_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
          fi

          # Printing the calculated version
          echo "Calculated version: $NEW_ARTIFACT_VERSION"

          # Store the NEW_ARTIFACT_VERSION for next steps
          echo "NEW_ARTIFACT_VERSION=$NEW_ARTIFACT_VERSION" >> $GITHUB_ENV

          jq --arg NEW_ARTIFACT_VERSION "$NEW_ARTIFACT_VERSION" '.version = $NEW_ARTIFACT_VERSION' manifest.json > manifest_updated.json
          mv manifest_updated.json manifest.json

      - name: Commit manifest.json
        if: env.bump != 'none' # Use env here instead of steps.determine-version.outputs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://${{ secrets.github_token }}@github.com/lakshaykaura/Yt_Max_Quality_Switcher.git
          git add manifest.json
          git commit -m "Artifact version bumped to ${{ env.NEW_ARTIFACT_VERSION }} in manifest.json [auto-bump]" # Use env variable here for the NEW_ARTIFACT_VERSION
          git push origin HEAD:${{ github.ref }}